-- This script has been refactored into the DDL, DML, functions, and triggers subdirectories.
-- Please refer to those directories for the specific SQL scripts.
-- To recreate the database structure and seed data, you would typically run scripts in the following order:
-- 1. DDL scripts (001_create_naves.sql, 002_create_tripulantes.sql, etc.)
-- 2. DML scripts (001_seed_naves.sql, 002_seed_missoes.sql, etc.)
-- 3. Functions scripts (check_nave_dependencies.sql)
-- 4. Triggers scripts (after_insert_nave_check_dependencies.sql)
