-- Inserção de Naves
    INSERT INTO naves (nome, tipo, fabricante, ano_construcao, status) VALUES
    ('Apollo 11', 'Tripulada', 'NASA', 1969, 'Aposentada'),
    ('Voyager 1', 'Sonda', 'NASA', 1977, 'Ativa'),
    ('Starship', 'Carga/Tripulada', 'SpaceX', 2023, 'Ativa'),
    ('Perseverance', 'Rover', 'NASA', 2020, 'Ativa'),
    ('Mars Reconnaissance Orbiter', 'Satélite', 'NASA', 2006, 'Ativa'),
    ('James Webb', 'Telescópio Espacial', 'NASA/ESA/CSA', 2021, 'Ativa'),
    ('Mars Odyssey', 'Sonda', 'NASA', 2001, 'Ativa'),
    ('Mars Express', 'Sonda', 'ESA', 2003, 'Ativa'),
    ('Mars Global Surveyor', 'Sonda', 'NASA', 1996, 'Finalizada'),
    ('Curiosity', 'Rover', 'NASA', 2011, 'Ativa'),
    ('Hubble', 'Telescópio', 'NASA/ESA', 1990, 'Ativa'),
    ('Challenger', 'Ônibus Espacial', 'NASA', 1982, 'Destruída'),
    ('Discovery', 'Ônibus Espacial', 'NASA', 1983, 'Aposentada'),
    ('Atlantis', 'Ônibus Espacial', 'NASA', 1985, 'Aposentada'),
    ('Spirit', 'Rover', 'NASA', 2003, 'Inativa'),
    ('Opportunity', 'Rover', 'NASA', 2003, 'Inativa'),
    ('New Horizons', 'Sonda', 'NASA', 2006, 'Ativa'),
    ('Cassini', 'Sonda', 'NASA/ESA/ASI', 1997, 'Finalizada'),
    ('Juno', 'Sonda', 'NASA', 2011, 'Ativa'),
    ('Millennium Falcon', 'Carga/Tripulada', 'Corellian Engineering Corporation', 1977, 'Ficcional'),
    ('Enterprise NCC-1701', 'Exploração', 'Starfleet', 2265, 'Ficcional'),
    ('X-Wing', 'Caça', 'Incom Corporation', 1977, 'Ficcional'),
    ('Nave dos Guardiões', 'Transporte', 'Guardiões da Galáxia', 2014, 'Ficcional'),
    ('Batmóvel Espacial', 'Veículo', 'Wayne Enterprises', 2022, 'Ficcional'),
    ('Nave dos Superamigos', 'Transporte', 'Superamigos', 1973, 'Ficcional'),
    ('Planet Express', 'Entrega', 'Planet Express', 2999, 'Ficcional'),
    ('Nave dos Jetsons', 'Familiar', 'Spacely Sprockets', 2062, 'Ficcional');
